# Generated by Django 5.0.2 on 2024-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanhistory',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
